- name: Check if current dir exists
  stat:
    path: "{{ app_current_dir }}"
  register: current_dir

- name: Migrate legacy structure
  include_tasks: migrate.yml
  when: current_dir.stat.exists == false

- name: Create project deployment structure
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0755
  with_items: ["{{ app_releases_dir }}", "{{ app_shared_dir }}/var/security-advisories"]
