---
server:
    packages: [curl, wget, git, subversion, vim, acl, bzip2, software-properties-common]
    timezone: Europe/Warsaw
    locale: en_US en_US.UTF-8 pl_PL pl_PL.UTF-8

system_user: repman
app_git_repo: 'https://github.com/repman-io/repman'
app_git_version: master
app_version: "{{ app_git_version }}"
app_root: /var/www/repman
app_current_dir: "{{ app_root }}/current"
app_shared_dir: "{{ app_root }}/shared"
app_releases_dir: "{{ app_root }}/releases"
app_keep_releases: 5
# This will be changed for version sha
app_current_release_dir: "{{ app_releases_dir }}/{{ app_version }}"
app_shared_resources:
    - 'var/log'
    - 'var/proxy'
    - 'var/repo'
    - 'var/security-advisories'
    - 'var/instance-id'

app_secret: "{{ lookup('env', 'REPMAN_APP_SECRET') or 'c6bd0523-77dd-4201-9c62-47a71234d0a5' }}"
server_hostname: 'repman.io'

# Add this to allow make requests only from proxy
nginx_proxy_secret: "{{ lookup('env', 'REPMAN_PROXY_SECRET') or '' }}"
nginx_client_max_body_size: 200M
app_message_consumers_name: message-consumer

# Database
db_host: localhost
db_port: 5432
db_name: main
db_user: repman
db_password: "{{ lookup('env', 'REPMAN_DB_PASSWORD') or 'password' }}"

# Postgres
postgresql_version: 11
postgresql_port: "{{ db_port }}"
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_ctype: 'en_US.UTF-8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_service_enabled: true

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_databases:
  - name: "{{ db_name }}"
    owner: "{{ db_user }}"
    uuid_ossp: yes

postgresql_users:
  - name: "{{ db_user }}"
    pass: "{{ db_password }}"

postgresql_user_privileges:
  - name: "{{ db_user }}"
    db: "{{ db_name }}"
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags

