on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  job:
    name: "Security"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          show-progress: false

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '7.4.2'

      - name: "Run composer audit"
        run: "composer audit --no-dev --locked"
